<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1 Login then add new candidate then modify it</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c606fdde-75b3-440f-a37b-b62a934816df</testSuiteGuid>
   <testCaseLink>
      <guid>c6e10f64-3e07-44b5-8d77-4c20756eb282</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1_Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61862d36-5f48-4ce7-9558-e579dd788da6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>575caa9c-860e-414c-ba0a-f4a6b89471ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b77d0ec1-a663-4f55-a455-507caa82bff6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94372df4-3a49-49d1-bbb6-7f1a7f9aed3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC2_Add candidate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcabf8f7-9645-4940-b38a-374a220da307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c213d61a-2522-4928-bd32-9596753150ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57c87834-9a20-4bfd-a329-0e79bdb7d6a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc459fc-36f5-405b-b34e-10a38b8dba8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fc068e8-41d4-43e5-aecc-dd740cefdab2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC3_ Show and Modify candidate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ffecca7-038c-478f-96b4-8f8f61fcd23e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
